### ISSUE TITLE
哥们，能不能加您一下？给我没有做过的作业行吗？

### ISSUE THREAD

**Issue by wo315** [before-Sunrise/cs106B-2020summer#1]
Assignment4我没有starter-code。您能帮我一下吗？
我的邮箱：wangyangstayfoolish@gmail.com
非常感谢。

**Comment by before-Sunrise** [comment]
我也只有做完的code了，你可以把我写的删了。其实我更推荐你学cs61b 2019spring的，知识量和练习量都更大一些

**Comment by wo315** [comment]
好的非常感谢您的回复！
