### ISSUE TITLE
Hello! Could you provide me the resources of CS106B?

### ISSUE THREAD

**Issue by Ealien** [before-Sunrise/cs106B-2020summer#2]
I'm learning CS106B, but resources need to be logged in to download. Could you provide me the resources of CS106B?

**Comment by before-Sunrise** [comment]
In fact I recommend you study cs61B 2019 spring instead，the resource is open ，and is more challenging than cs106B（which means you can learn more and practice more)

**Comment by Ealien** [comment]
Thank you very much for your suggestions, but I want to be able to learn C++ at the same time. My email is guotao967@gmail.com, which can be used for learning and communication.

**Comment by before-Sunrise** [comment]
> Thank you very much for your suggestions, but I want to be able to learn C++ at the same time. My email is [guotao967@gmail.com](mailto:guotao967@gmail.com), which can be used for learning and co

**Comment by before-Sunrise** [comment]
https://web.stanford.edu/class/archive/cs/cs106b/cs106b.1208/
This is the website when I learn this couse，but the assignmet starter code is not available anymore. u can use my code and delete the answer

**Comment by Ealien** [comment]
Thanks for your help.
